### PR TITLE
add repository link to nuspec files

### PR DESCRIPTION
**Pull request by jeremyhayes**
https://docs.microsoft.com/en-us/nuget/reference/nuspec#repository

Adding the repository link allows direct linking from the NuGet gallery to the source repository.

It is also how tools like [renovate-bot](https://github.com/renovatebot/renovate) are able to group "monorepo" packages for updates which must be performed in tandem.

### CODE REVIEW

**Comment by odinserj** [comment]
Thanks @jeremyhayes, but will it work? https://docs.microsoft.com/en-us/nuget/reference/nuspec#repository mentions that "It should not be an html page as this is meant for the computer", and has the following example (please see the ".git" suffix):

```xml
<repository type="git" url="https://github.com/NuGet/NuGet.Client.git" branch="dev" commit="e1c65e4524cd70ee6e22abe33e6cb6ec73938cb3" />
```

**Comment by jeremyhayes** [comment]
Nice catch @odinserj! Updated and rebased.

**Comment by jeremyhayes** [comment]
Hmm...the travis build failures don't seem related to this change.

Not sure what to do here. @odinserj any suggestions?

**Comment by odinserj** [comment]
This time errors were due to Mono installation failure and integration test particularities when testing Hangfire.SqlServer, so I've retried them.

**Pull request merged**
