### PR TITLE
fix for log4net for dotnet standard

### LINKED ISSUE #1095: Integration with log4net in dotnet core 2.0
I have following code
```
static void Main(string[] args)
        {

            // log4net
            var logRepository = LogManager.GetRepository(Assembly.GetEntryAssembly());
            XmlConfigurator.Configure(logRepository, new FileInfo("log4net.config"));
            log = LogManager.GetLogger(Assembly.GetEntryAssembly(), typeof(Program).Namespace);

            // HangFire
            GlobalConfiguration.Configuration
                .UsePostgreSqlStorage(ConfigurationManager.ConnectionStrings[Constants.ConnectionSettingKeys.HANGFIRE_NAME].ConnectionString);
            // BackgroundJob.Enqueue(() => Process().GetAwaiter().GetResult());
            RecurringJob.AddOrUpdate(typeof(Program).Namespace, () => Process().GetAwaiter().GetResult(), Cron.Minutely);
            using (var server = new BackgroundJobServer())
            {
                Console.WriteLine("Hangfire Server started. Press any key to exit...");
                Console.Read();
            }
        }
```

when I start the app, I get following error
```
Exception occured resolving a log provider. Logging for this assembly Hangfire.Core, Version=1.6.17.0, Culture=neutral, PublicKeyToken=null is disabled. System.ArgumentNullException: Value cannot be null.
Parameter name: method
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at Hangfire.Logging.LogProviders.Log4NetLogProvider.GetGetLoggerMethodCall()
   at Hangfire.Logging.LogProviders.Log4NetLogProvider..ctor()
   at Hangfire.Logging.LogProvider.<>c.<.cctor>b__10_2()
   at Hangfire.Logging.LogProvider.ResolveLogProvider()
```

can anyone help me with this error?

### PR DESCRIPTION
**Pull request by evollu**
`GetLogger(string name)` no longer exists in log4net dotnet core. Use `GetLogger(Assembly assembly, string name)` as fallback

fixes #1095

### CODE REVIEW

**Comment by pieceofsummer** [comment]
Any reason it doesn't simply resolve different methods based on the preprocessor directive?
```c#
#if NETFULL
MethodInfo method = logManagerType.GetRuntimeMethod("GetLogger", new[] { typeof(string) });
MethodCallExpression methodCall = Expression.Call(null, method, new Expression[] { nameParam });
#else
MethodInfo method = logManagerType.GetRuntimeMethod("GetLogger", new[] { typeof(Assembly), typeof(string) });
MethodCallExpression methodCall = Expression.Call(null, method, new Expression[] { Expression.Constant(typeof(Log4NetLogProvider).GetTypeInfo().Assembly), nameParam });
#endif
```

**Comment by evollu** [comment]
No reason. I can change the code

**Comment by pieceofsummer** [comment]
I checked the log4net repo, and `GetLogger(Assembly, string)` method exists there from the very start. So I believe we can safely use this overload for all cases.

**Comment by evollu** [comment]
I don't know where these 56 files changes come from.
opened a new PR change log4net method #1134

**Pull request closed without merging**
