### PR TITLE
Fix for #500, BackgroundJob.Delete may hang forever

### PR DESCRIPTION
**Pull request by danoleary**
Added null handling to prevent an infinite loop if an attempt is made to delete a job
that doesn't exist

### CODE REVIEW

**Comment by captain828** [comment]
Is the loop even needed any more?
Also, what is the scenario for jobs with no state?

**Comment by danoleary** [comment]
With the change I have made, the loop will only come into play when context.Connection.GetJobData(context.BackgroundJobId) returns a job with a null or empty state. 

Given I haven't been able to find any mention of issues caused by empty states causing Hangfire to hang, should we leave this behaviour as is?

**Comment by captain828** [comment]
Since I don't know the full implementation of the cancellation token, I can't tell if this is going to break it or not.

As far as I can understand, a job is always in a given state, as such:
```
if (jobData == null)
{
      return null;
}

if (jobData != null && !String.IsNullOrEmpty(jobData.State))
{
      return jobData;
}
```
will guarantee an exit, which in turn means that:
```
if (context.CancellationToken.IsCancellationRequested ||
    context.CancellationToken == CancellationToken.None)
{
       return null;
}
```
will never be executed, potentially breaking the cancellation token feature.

**Comment by danoleary** [comment]
If a job is guaranteed to have a state, could we just simplify the method to this?
````
private static JobData GetJobData(StateChangeContext context)
{
   if (context.CancellationToken.IsCancellationRequested ||
                    context.CancellationToken == CancellationToken.None)
   {
       return null;
   }

   return context.Connection.GetJobData(context.BackgroundJobId);
   }
````

**Comment by captain828** [comment]
Yeah, that should work just fine.

**Comment by captain828** [comment]
Looks like the RabbitMQ storage provider was not very happy with this :)

**Comment by danoleary** [comment]
It does! I've ran all of the tests successfully locally though, so I'm not really sure how to troubleshoot this. Do you know if there's a way of kicking off another build without making changes?

**Comment by captain828** [comment]
Yeah, looks like the build errored, not failed.

Close the PR and then re-open it. This should force a new build.

**Comment by captain828** [comment]
Same issue:
`Test execution time exceeded: 30000ms`

@odinserj - could you have a quick look to see if the RabbitMQ server is reachable?

**Comment by danoleary** [comment]
Thanks for looking into this, shall we leave this pull request as it is then?

**Comment by captain828** [comment]
Could you kindly change line 5 in https://github.com/HangfireIO/Hangfire/blob/master/.travis.yml to `sudo: required` and commit it?

If it still errors out, then there really isn't much else we can do.

**Comment by captain828** [comment]
There we go! :+1:

**Comment by odinserj** [comment]
This issue is already resolved in PR #469. I've just released [1.5.4](https://github.com/HangfireIO/Hangfire/releases/tag/v1.5.4) that fixes the problem.

**Comment by odinserj** [comment]
Infinite loop is still required, because some queue providers, such as Hangfire.SqlServer.MSMQ and Hangfire.SqlServer.RabbitMQ may insert a background job identifier to a queue (and make it available for workers) *before* background job is saved to a job storage. 

This may happen, because background job creation is held within a transaction, and queue provider may insert a job before that transaction is committed. And this results into issue described in #294.

**Comment by captain828** [comment]
I knew it was there for a reason :)

Thanks for looking into this and for pushing a new version!

**Comment by odinserj** [comment]
Yep, but I'm ashamed to release the fix several months after it was committed to the master :frowning:

**Comment by captain828** [comment]
Well you definitely shouldn't feel ashamed that you created such an amazing and easy-to-use scheduler!

**Pull request closed without merging**
