### PR TITLE
Dashboard Stats Polling Interval

### PR DESCRIPTION
**Pull request by tristal**
Adding support for a configurable dashbaord stats polling interval;

Not sure about the process for opening PR's vs issues.  Please let me know if you would prefer to have an issue for discussion before PR's in the future.

### CODE REVIEW

**Comment by tristal** [comment]
Not sure about the process for opening PR's vs issues.  Please let me know if you would prefer to have an issue for discussion before PR's in the future.

**Comment by tristal** [comment]
Hi, is there any chance this PR could be looked at and possibly merged?

**Comment by gandarez** [comment]
+1

**Comment by dazinator** [comment]
+1 I'd love to see this. The amount of requests from the dashboard to the web server on "/hangfire/stats" is huge, and we could do with reducing this, as we have cookie decryption code running against each request in order to authenticate the request which is quite cpu intensive.

**Comment by tristal** [comment]
Just following up on this, again?

**Comment by odinserj** [comment]
@tristal, sorry for the loooong delay :-( I'll be happy to merge this PR, but could you please target it to the `dev` branch?

**Comment by odinserj** [comment]
I've merged this PR into the `dev` branch, please see the commit 0fd1a1b88bc21e2de64dd18e191d21e9713c3626. Thank you for the PR! This feature will be released in 1.6.0.

**Comment by tristal** [comment]
Sorry, @odinserj -- time has gotten away from me.  Thanks for handling that.

**Pull request closed without merging**
