### PR TITLE
Update gitignore and remove .lock.json files

### PR DESCRIPTION
**Pull request by stevetsang**
Updated gitignore to ignore all .lock.json files and removed *.project.lock.json files.

### CODE REVIEW

**Comment by odinserj** [comment]
Hi @stevetsang! Would you like to remove all the other `*.project.lock.json` files as well?

**Comment by stevetsang** [comment]
I think that is the only that is in source but will check the rest!

**Comment by stevetsang** [comment]
Yeah found two others and removed them :)

**Comment by odinserj** [comment]
:+1:, but there are also `Hangfire.AspNetCore\project.lock.json`, `Hangfire.SqlServer\project.lock.json`, `Hangfire.Core\project.lock.json` :smile:

**Comment by stevetsang** [comment]
just checked the repo and couldn't find Hangfire.AspNetCore\project.lock.json, Hangfire.SqlServer\project.lock.json, Hangfire.Core\project.lock.json

**Comment by odinserj** [comment]
Sure, looks like they are already ignored. Thanks for the PR, merging!

**Comment by odinserj** [comment]
Btw, congratulations with the first merged PR! :tada: :fireworks:

**Pull request merged**
