### PR TITLE
Feature/disable recurring jobs

### PR DESCRIPTION
**Pull request by Kithuldeniya**
**Requested issue : Disable Recurring Job from Dashboard #2289**

### Initiating a recurrent job
When creating a recurrent job, you can use RecurringJobOptions to disable the job. By default, this value is set to false, ensuring that existing jobs remain unaffected.
image

### Visual in the dashboard
Disabled jobs can be identified in the dashboard by the ‘Disabled’ tag, which appears with a tooltip under the ‘Next Execution’ column.
image

### Action popups
The enable and disable actions will trigger a popup to obtain user confirmation.
image
image

### CODE REVIEW

**Comment by DCarlson12** [comment]
Duplicate of #2431, pretty much copying my PR not even 24h later with some changed method names...

**Comment by Kithuldeniya** [comment]
Don’t assume that no one will need to refer to your pull request to come up with method names if you’re following the existing method standards.

**Comment by DCarlson12** [comment]
> Don’t assume that no one will need to refer to your pull request to come up with method names if you’re following the existing method standards.

It’s not just that, you copied almost my entire implementation, even down to the very glyph for the icons on the buttons. Just a little suspicious…

**Comment by Kithuldeniya** [comment]
Closing PR as this PR has the similer feature to https://github.com/HangfireIO/Hangfire/pull/2431

**Pull request closed without merging**
