### PR TITLE
Adjusting deserialization of datetime to use RoundTripKind

### PR DESCRIPTION
**Pull request by plaisted**
Proposed fix for issue #970.

### CODE REVIEW

**Comment by odinserj** [comment]
I looked at the problem more closely, and realized this fix is not enough. Since you may not know about previous formats, I've implemented some tests for you, please add them to your PR. They will require some more work to be made.

```csharp
[Fact]
public void Deserialize_CorrectlyDeserializes_LocalDateTimeArguments_ConvertedToRoundtripFormat()
{
    var value = DateTime.Now;
    var serializedData = new InvocationData(
        typeof(InvocationDataFacts).AssemblyQualifiedName,
        nameof(DateTimeMethod),
        JobHelper.ToJson(new[] { typeof(DateTime) }),
        JobHelper.ToJson(new[] { value.ToString("o", CultureInfo.InvariantCulture) }));

    var job = serializedData.Deserialize();

    Assert.Equal(value, (DateTime)job.Args[0]);
}

[Fact]
public void Deserialize_CorrectlyDeserializes_UtcDateTimeArguments_ConvertedToRoundtripFormat()
{
    var value = DateTime.UtcNow;
    var serializedData = new InvocationData(
        typeof(InvocationDataFacts).AssemblyQualifiedName,
        nameof(DateTimeMethod),
        JobHelper.ToJson(new [] { typeof(DateTime) }),
        JobHelper.ToJson(new [] { value.ToString("o", CultureInfo.InvariantCulture) }));

    var job = serializedData.Deserialize();

    Assert.Equal(value, (DateTime)job.Args[0]);
}

[Fact]
public void Deserialize_CorrectlyDeserializes_LocalDateTimeArguments_ConvertedToOldFormat_WithLoweredPrecision()
{
    var value = DateTime.Now;
    var serializedData = new InvocationData(
        typeof(InvocationDataFacts).AssemblyQualifiedName,
        nameof(DateTimeMethod),
        JobHelper.ToJson(new[] { typeof(DateTime) }),
        JobHelper.ToJson(new[] { value.ToString("MM/dd/yyyy HH:mm:ss.ffff", CultureInfo.InvariantCulture) }));

    var job = serializedData.Deserialize();

    var actualValue = (DateTime)job.Args[0];

    Assert.Equal(value.Year, actualValue.Year);
    Assert.Equal(value.Month, actualValue.Month);
    Assert.Equal(value.Day, actualValue.Day);
    Assert.Equal(value.Hour, actualValue.Hour);
    Assert.Equal(value.Minute, actualValue.Minute);
    Assert.Equal(value.Second, actualValue.Second);
}

[Fact]
public void Deserialize_CorrectlyDeserializes_UtcDateTimeArguments_ConvertedToOldFormat_WithLoweredPrecision()
{
    var value = DateTime.UtcNow;

    var serializedData = new InvocationData(
        typeof(InvocationDataFacts).AssemblyQualifiedName,
        nameof(DateTimeMethod),
        JobHelper.ToJson(new[] { typeof(DateTime) }),
        JobHelper.ToJson(new[] { value.ToString("MM/dd/yyyy HH:mm:ss.ffff", CultureInfo.InvariantCulture) }));

    var job = serializedData.Deserialize();

    var actualValue = (DateTime) job.Args[0];

    Assert.Equal(value.Year, actualValue.Year);
    Assert.Equal(value.Month, actualValue.Month);
    Assert.Equal(value.Day, actualValue.Day);
    Assert.Equal(value.Hour, actualValue.Hour);
    Assert.Equal(value.Minute, actualValue.Minute);
    Assert.Equal(value.Second, actualValue.Second);
}
```

**Comment by plaisted** [comment]
I'll probably have time this weekend to look at this again.

**Comment by plaisted** [comment]
I've updated the PR to take into account your requested changes.

I don't think we can use TypeConverter for DateTime as it doesn't respect the original DateTimeKind the DateTime was in.  As a result I've moved `ParseDateTimeArgument` to be the primary method for DateTime deserialization after the JsonHelper fails.

I don't think any types other than the custom formatted DateTime string (without quotations) would fail the JsonHelper deserialization but I left TypeConverter in as a fallback for NETFULL just in case there are other scenarios I couldn't think of where other Types that fail Json Deserialization in order to keep the behavior consistent with previous version.

**Comment by odinserj** [comment]
Great work @plaisted, thank you for your effort! This fix will be available in 1.6.16 shortly.

**Pull request merged**
