### PR TITLE
[WIP] Implemented Manual Job (With tests)

### PR DESCRIPTION
**Pull request by BeeHiveJava**
See #830. All credits go out to @reaction1989, who provided the original implementation. All I did is added tests in hope to get this feature going sooner!

> see #382
> 
> Rewritten the commits of @gandarez see
> https://github.com/gandarez/Hangfire/tree/manual-job
> 
> Changes are not tested by now.

### CODE REVIEW

**Comment by BeeHiveJava** [comment]
@odinserj This line specifically fails for some reason, it happened in another PR too (#1029), not too certain why.
https://github.com/HangfireIO/Hangfire/blob/6525aa314f65d1a029863928edf8c9cfc18ec30d/tests/Hangfire.SqlServer.Tests/SqlServerWriteOnlyTransactionFacts.cs#L55

**Comment by danielcor** [comment]
I don't get it.   What about this is so different than already exists?

**Comment by BeeHiveJava** [comment]
@danielcor, As @gandarez once explained: a manual job has to be manually triggered from the dashboard (or code) in order to be executed. Unlike a recurring or scheduled job, it does not execute on a predefined time.

In our usecase this is very useful for testing and cleaning purposes.

**Comment by dcorbett-fivebridgesllc** [comment]
Normal jobs are triggered from code to be executed….  And this extension allows one to manually queue jobs:

https://github.com/tracstarr/Hangfire.Core.Dashboard.Management

This enhancement doesn’t require a modification to Hangfire.
So I still don’t understand the benefit.

**Comment by BeeHiveJava** [comment]
I can't believe we've overlooked that one. That seems to be about perfect for our use case, thanks! I'll make sure to comment it on the other PR as well, so that future searchers may be helped out perhaps.

**Pull request closed without merging**
