### PR TITLE
Case sensitive changes for BIN collation SQL databases

### PR DESCRIPTION
**Pull request by ilessa**
Fixes for issue #371 - will work on all databases however changes are significant for users with a BIN collation SQL server.

### CODE REVIEW

**Comment by odinserj** [comment]
:heart: these changes. Why did you upgrade RabbitMQ client to 1.5.2?

**Comment by ilessa** [comment]
I didn't have RabbitMQ on my machine and NuGet gave me 1.5.2.

**Comment by odinserj** [comment]
Hm, strange, I've thought that NuGet installs the exact version specified in the project. Would you like to revert the `RabbitMq.Client` upgrade?

**Comment by odinserj** [comment]
Btw, we can also create case sensitive database for unit-tests for more strict tests. Would you like to do this?

**Comment by ilessa** [comment]
Ok, I think I've reverted the changes (first time I've been using GIT so bear with me)
Let me know if this is ok please.
I have the Hangfire.SqlServer.Tests database on my BIN collation server if that's what you mean?

**Comment by odinserj** [comment]
Don't worry, all is ok :smile: `CleanDatabase` has a simple script to create database, and we can pass the CS collation:

```sql
CREATE DATABASE CaseSensitive COLLATE SQL_Latin1_General_CP1_CS_AS
```

**Comment by ilessa** [comment]
Ok, I use Latin1_General_BIN if that’s any help

**Comment by odinserj** [comment]
What do you mean regarding tempdb?

**Comment by ilessa** [comment]
The tempdb database is built each time SQL Server is started, and has the same default collation as the model database, which is typically the same as the default collation of the instance. If you create a user database and specify a different default collation than model, the user database has a different default collation than tempdb. All temporary stored procedures or temporary tables are created and stored in tempdb, which means that all implicit columns in temporary tables and all coercible-default constants, variables, and parameters in temporary stored procedures have different collations than comparable objects created in permanent tables and stored procedures.

Just trying to prevent any collation conflicts if you use any temporary tables in the code :)

**Comment by odinserj** [comment]
Time to merge this awesome PR! :heart:

**Pull request merged**
