### PR TITLE
Add reschedule functionality to BackgroundJob

### PR DESCRIPTION
**Pull request by chrischu**
We need the ability to reschedule jobs (similar to the requeue functionality) so we decided to contribute the code. I hope that's ok. Hopefully I added all the necessary tests, if not please let me know :).

### CODE REVIEW

**Review by odinserj — COMMENTED** [review]
Thanks for the changes, look good to me. Since they don't break anything and quite simple, I can schedule this to 1.7.34 version. However may I ask you to make 2 slight changes to the PR?

* Rename `Requeue` to `Reschedule` in two places in the `BackgroundJob` class.
* Use 4 spaces instead of 2 in the changed lines.

**Comment by chrischu** [comment]
Thanks @odinserj for the quick reply!

I made the changes you suggested, let me know if I missed something or if there's any other changes you'd like :)!

**Review by odinserj — DISMISSED** [review]
Thanks, LGTM

**Comment by odinserj** [comment]
@chrischu, may I also ask you to base changes on the `1.7.X` branch instead of the `master` one? I'm now preparing the final release of 1.8.0 and landed it on `master` already.

**Comment by chrischu** [comment]
Done!

**Comment by luizfbicalho** [comment]
This feature changed the problem in #1976 ?

The state got too big in my database

**Pull request merged**
