### PR TITLE
Add JobDisplayNameAttribute

### PR DESCRIPTION
**Pull request by pieceofsummer**
This should have been done a long time ago :)

Supports formatting:
```c#
[JobDisplayName("Test job ({0})")]
public static void TestJob(int arg)
```

Supports localization:
```c#
[JobDisplayName("TestJob_DisplayName", ResourceType = typeof(MyResources))]
public static void TestJob(int arg)
```

### CODE REVIEW

**Comment by odinserj** [comment]
Finally merged, @pieceofsummer, thanks for your efforts! 👍 👍 👍

**Comment by pieceofsummer** [comment]
@odinserj I wonder if this should take precedence before display name provider? If yes, then NETFULL `DisplayNameAttribute` should too.

Looking back at this PR, I also think maybe we should unseal `JobDisplayNameAttribute` and make `Format` method virtual, so users may easily inherit custom attributes from it and implement their own naming. What do you think?

**Comment by odinserj** [comment]
Right! I've just made the corresponding commits to implement these ideas.

**Comment by pieceofsummer** [comment]
Great! Now I think the only thing left (before the major update to fully async model in 2.0) is to cancel the `CancellationToken` when the job is deleted from dashboard :)

**Comment by odinserj** [comment]
I'll mark it with the 1.7.0 milestone then and check a bit later ("later" sounds dangerous, he-he) 😃

**Comment by ernecastro** [comment]
Hi all, I don't if I'm missing something, but this feature does not seem to work for me.

Having this method:

`        [JobDisplayName("Test job ({0})")]
`
`       public static void ExecuteJob(int p)
`
`       {
``          ...
`       }

 
Gives this name in the dashboard:

  Test job (System.Object[])

**Comment by pieceofsummer** [comment]
@ernecastro see #1136. Fixed in `dev` branch already, will be included in the next beta.

**Comment by rfrancisco** [comment]
When can we expect the next beta with this fix?

**Comment by joshuagriffin** [comment]
We are waiting for this as well

**Comment by Shamshiel** [comment]
Does this only work with static methods? I'm not able to get it to work with my non-static methods.

**Comment by freeflyrw** [comment]
Same issue for me. @Shamshiel. @pieceofsummer No joy. Method call below not static. Had you any luck with this?

[JobDisplayName("Perform CatNet Analysis - CatNetJobQueueId {0}")]
Task PerformCatNetAnalysis(string catNetJobQueueId, string userEmail, string locationName);

**Comment by freeflyrw** [comment]
Ahhh...had the attribute at interface rather than class level. All good now!

**Comment by taylor-viventium** [comment]
This seems to be broken. It has no effect on my job name. Tried both DisplayName and JobDisplayName with a string value.

**Comment by odinserj** [comment]
If you are using a base class or interface for your background jobs, please try putting the attributes there instead of an implementation class.

**Pull request merged**
