### PR TITLE
Passing params in job creation phase

### PR DESCRIPTION
**Pull request by brian-knoll-micronetonline**
Updated PR of https://github.com/HangfireIO/Hangfire/pull/570

### CODE REVIEW

**Comment by odinserj** [comment]
Thanks @brian-knoll-micronetonline. Unfortunately it contains breaking changes, so I'm unable to land it before Hangfire 2.0.

**Comment by brian-knoll-micronetonline** [comment]
@odinserj Thanks for the reply. So will it get accepted after hangfire 2.0? That would be great if it does. If not is there any change i should make to get it accepted?

**Comment by mjl321** [comment]
Is this still something being considered for 2.0? Would be useful functionality to have, it's not listed here though: https://github.com/HangfireIO/Hangfire/milestone/17

**Comment by brian-knoll-micronetonline** [comment]
@mjl321 equivalent functionality was added in https://github.com/HangfireIO/Hangfire/releases/tag/v1.8.0

**Comment by mjl321** [comment]
Thanks for the quick reply. I'm struggling to find any documentation / code for this functionality. I'm adding a recurring job, but can't see any overloads for RecurringJob.AddOrUpdate that allow the setting of Job parameters, I can't spot anything in the BackgroundJobClient either. It looks like there's a new parameter defined in IBackgroundJobClientV2. I'd be grateful if you could point me in the right direction for adding job parameters when creating a recurring job.

**Comment by mjl321** [comment]
Awesome, thank you. I've changed it so the recurring job now calls an intermediary method which then uses the new(?) IBackgroundJobClientV2 to create the job with the parameter (tenantid). 

So I've now got a Recurring Job which calls an AddJobForTenant method with the tenant info and a class that provides the actual method to call (as couldn't pass delegate as job method parameter), which creates the actual job (with the tenant id as a job parameter which is later used to set the tenant context when the job is run).

**Pull request closed without merging**
