### PR TITLE
Features: use RecurringJobAttribute to build RecurringJob automatically.

### PR DESCRIPTION
**Pull request by icsharp**
# We can create RecurringJob automatically using attribute `RecurringJobAttribute`

Usage as below:

```csharp
public class RecurringJobService
{
    [RecurringJob("*/1 * * * *")]
    [DisplayName("InstanceTestJob")]
    [Queue("jobs")]
    public void InstanceTestJob(PerformContext context)
    {
        context.WriteLine($"{DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss")} InstanceTestJob Running ...");
    }

    [RecurringJob("*/5 * * * *")]
    [DisplayName("JobStaticTest")]
    [Queue("jobs")]
    public static void StaticTestJob(PerformContext context)
    {
        context.WriteLine($"{DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss")} StaticTestJob Running ...");
    }
}

public interface ISampleService
{
    /// <summary>
    /// simple job test
    /// </summary>
    /// <param name="context"></param>
    [RecurringJob("0 4 1 * *")]
    [AutomaticRetry(Attempts = 3)]
    [DisplayName("SimpleJobTest")]
    [Queue("jobs")]
    void SimpleJob(PerformContext context);
}
```

In app start, we can use extension method `UseRecurringJob(this IGlobalConfiguration configuration, params Type[] types)`
to build `RecurringJob`, more details is [here](https://github.com/icsharp/Hangfire.Topshelf).

```csharp
GlobalConfiguration.Configuration.UseRecurringJob(typeof(RecurringJobService), typeof(ISampleService));
```

### CODE REVIEW

**Comment by odinserj** [comment]
Hi @icsharp, thank you for the contribution :+1:! Looks like this feature may be implemented as an extension for Hangfire, that is fully separated from the core. Such projects already exist, please see http://hangfire.io/extensions.html for examples. I'd like to keep this repository as simple as possible, moving all the optional extensions to their own repositories and packages. What do you think?

**Comment by icsharp** [comment]
@odinserj 
thanks for u reply, move this feature as optional extensions is proper. I will do this later.

**Comment by odinserj** [comment]
@icsharp, feel free to ask any question regarding packaging here!

**Comment by icsharp** [comment]
@odinserj 
Here is the [repo](https://github.com/icsharp/Hangfire.RecurringJobExtensions) for this feature.
[PR](https://github.com/HangfireIO/Hangfire/pull/725) to http://hangfire.io/extensions.html.

**Pull request closed without merging**
