### PR TITLE
Add queue name validation to the RecurringJobScheduler class

### PR DESCRIPTION
**Pull request by pzielinski86**
I moved logic of validation to QueueValidator. It should fix the issue when adding a job with an invalid name is possible, but triggering it always fails without any exception.

### CODE REVIEW

**Comment by pzielinski86** [comment]
Any thoughts?

**Comment by odinserj** [comment]
@pzielinski86, what is the reason of putting the logic into a separate public class with a single method?

**Comment by odinserj** [comment]
However, I like to see the queue name check in the `RecurringJobManager` class :heart:

**Comment by pzielinski86** [comment]
@odinserj:
I didn't want to duplicate the validation logic in 2 places. Maybe there is a better place, like an existing namespace\class?

What do you think?

**Comment by odinserj** [comment]
We can just change the visibility of the method from `private` to `internal` or `public` without adding new entities (as they add unnecessary complexity in this case). I don't see any advantages of making it public, but leaving this decision to you!

**Comment by pzielinski86** [comment]
I think you are right. EnqueuedState is used in RecuringJobManager anyway so I will make it internal static in EnqueuedState.

**Comment by odinserj** [comment]
Ok, will wait for the updated PR!

**Comment by pzielinski86** [comment]
I marked the method as static and removed the created before class.

**Comment by odinserj** [comment]
Thanks, @pzielinski86! I've just merged this PR. Will be released with 1.5.7

**Pull request merged**
