### PR TITLE
Scheduling to specific queue

### PR DESCRIPTION
**Pull request by cdschneider**
Although it looks like it's been partially attempted in the past, solving #748 (providing support for scheduling jobs to a non-default queue).

This change includes:

* An added `CandidateQueue` property to `ScheduledState` (that also gets serialized/persisted w `Job`s `StateData`
* A new element in the `ScheduledState`s details section that includes a link to the actual queue's HF details page
* Optional `queue` parameter to `BackgroundJobClientExtensions` on all `Schedule` methods

Here is an example of the scheduling with this feature:

```
BackgroundJob.Schedule(
    () => Console.WriteLine("Hello, world!"),
    TimeSpan.FromHours(1), 
    "custom_queue");
```

HF job details when in "Scheduled" state looks like the following:

image

### CODE REVIEW

**Comment by Nexsus94** [comment]
Any updates on this?

**Comment by pieceofsummer** [comment]
@cdschneider thanks for your work.

This would require a careful review before merging. But adding arguments with default value is absolutely a no go, as it breaks binary compatibility. Would you please change them into the corresponding methods' overloads instead?

**Comment by drauch** [comment]
Is there any work going on regarding this pull request? It would probably fix our issue #1159, which is why we're interested in it. Ping @cdschneider

**Comment by cdschneider** [comment]
@drauch sorry for delay on this. @pieceofsummer I've refreshed my branch from `Hangfire:dev` and updated per your comments to remove default-parameters and made the appropriate `Schedule` method overloads in the `BackgroundJobClientExtensions` class. 

Please let me know what you think and if you'd like to see more updates prior to merging.

**Comment by weyert** [comment]
How can we progress this PR?

**Comment by willemduncan** [comment]
Would like to see this feature as well. Don't want to hard code queue names in a function attribute, the chosen queue will depend on runtime variables which are only know during enqueue.

**Comment by willemduncan** [comment]
We run a filter that writes the queue name as job parameter, and then uses that to overwrite whatever hangfire decides should be the queue later. It's globally applied at app startup:

```cs
GlobalJobFilters.Filters.Add(new PreserveOriginalQueueFilter());
```

And looks like this:

```cs
/// <summary>
/// Job filter that preserves the job queue when changing state to 'Enqueued'.
/// </summary>
public class PreserveOriginalQueueFilter : IApplyStateFilter
{
    private const string ParameterName = "OriginalQueue";

    public void OnStateApplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
    {
        // Activating only when enqueueing a background job.
        if (context.NewState is EnqueuedState enqueuedState)
        {
            // Checking if an original queue is already set.
            var originalQueue = SerializationHelper.Deserialize<string>(context.Connection.GetJobParameter(context.BackgroundJob.Id, ParameterName));
            if (originalQueue != null)
            {
                // Override any other queue value that is currently set.
                enqueuedState.Queue = originalQueue;
            }
            else
            {
                // Queueing for the first time, we should set the original queue.
                context.Connection.SetJobParameter(
                    context.BackgroundJob.Id,
                    ParameterName,
                    SerializationHelper.Serialize(enqueuedState.Queue)
                );
            }
        }
    }

    public void OnStateUnapplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
    {
    }
}
```

**Comment by frankyjquintero** [comment]
@cdschneider  @odinserj What do we need to add this functionality, its use simplify dependencies in cleaner architecture

**Comment by odinserj** [comment]
Thanks for your patience. Upcoming 1.8.0 release will bring first-class support for custom default queues for background jobs so almost nothing is required:

```csharp
BackgroundJob.Schedule("critical", () => Console.WriteLine("Hi!"), TimeSpan.FromHours(1));
```

Queue is persisted with background job information itself so everything is preserved on automatic retries and other state changes. This feature is already available in the latest betas and will be released approximately next week.

**Comment by frankyjquintero** [comment]
Excellent news, I am looking forward to this new version. Thank you

**Comment by fbonjour81** [comment]
> Thanks for your patience. Upcoming 1.8.0 release will bring first-class support for custom default queues for background jobs so almost nothing is required:
> 
> ```cs
> BackgroundJob.Schedule("critical", () => Console.WriteLine("Hi!"), TimeSpan.FromHours(1));
> ```
> 
> Queue is persisted with background job information itself so everything is preserved on automatic retries and other state changes. This feature is already available in the latest betas and will be released approximately next week.

Great news @odinserj!!! Could we have some kind of conflict using QueueAttribute and PreserveOriginalQueueAttribute with this new version? The idea is remove them in the future

**Pull request closed without merging**
