### PR TITLE
remove the with tablock hint from the expiration cleanup

### PR DESCRIPTION
**Pull request by travisblakeney**

### CODE REVIEW

**Comment by travisblakeney** [comment]
This is for issue #313

**Comment by odinserj** [comment]
Please, re-target this PR to the `dev` branch

**Comment by travisblakeney** [comment]
retargeted it against the dev branch. Not sure why the readme.md file change came with it. If this is an issue just let me know.

**Comment by odinserj** [comment]
Travis, this is not a problem - there were some unmerged changes between dev and master. Thank you for this extra work

**Pull request closed without merging**
