### PR TITLE
Allow modification of the dashboard title

### PR DESCRIPTION
**Pull request by tbertenshaw**
We have several dashboards all exposed using ports and without meaningful urls. Allowing modification of the title on the dashboard to a more meaningful title than "Hangfire Dashboard" will make it easier to discover the purpose.

### CODE REVIEW

**Comment by tbertenshaw** [comment]
@odinserj is this change ok to merge to master? It seems a pretty risk free change?

**Comment by shorbachuk** [comment]
+1

**Comment by willchis** [comment]
+1 please

**Comment by zhiyuanzhang-unai** [comment]
can you merge this PR to v1.7.0-beta2 as well?

**Comment by diego-varela** [comment]
This pull request has been requested long time ago. When will this feature be released?

**Comment by danimr** [comment]
+1 please

**Comment by caioproiete** [comment]
Anything I can help with getting this PR merged? This feature would be very useful!!

**Comment by pmunin** [comment]
common guys,  it was submitted 1 year ago

**Comment by pmunin** [comment]
@tbertenshaw may be assigning reviewer could help?

**Comment by tbertenshaw** [comment]
> @tbertenshaw may be assigning reviewer could help?

not sure I have the ability to do that.

**Comment by caioproiete** [comment]
For others looking for a workaround to change the title of a Hangfire dashboard, whilst this PR is not merged, I've put together a simple library that does the job.

https://github.com/caioproiete/hangfire-dashboard-customize

[hangfire-dashboard-customize](https://github.com/caioproiete/hangfire-dashboard-customize)

Works with ASP .NET Core apps as well as with Owin-based apps.

---

**Comment by odinserj** [comment]
Thanks everyone, the change will be available in the 1.7.7 version.

**Pull request merged**
