### PR TITLE
Fix race condition in AspNetShutdownDetector and warnings

### PR DESCRIPTION
**Pull request by jr01**
Fixes https://github.com/HangfireIO/Hangfire/issues/1784

### CODE REVIEW

**Review by odinserj — APPROVED** [review]

**Review by odinserj — CHANGES_REQUESTED** [review]
Oh there are some build errors, please check AppVeyor build results

**Comment by jr01** [comment]
🤦 will fix

**Comment by odinserj** [comment]
No worries, the number of supported .NET frameworks have some drawbacks 🤷‍♂️

**Comment by jr01** [comment]
AppVeyor fails - it looks like it's flaky test day ❄️  😃

**Review by odinserj — APPROVED** [review]
Looks good, merging! :+1:

**Pull request merged**
