### PR TITLE
[WIP] Implemented Manual Job

### PR DESCRIPTION
**Pull request by reaction1989**
see #382

Rewritten the commits of @gandarez see 
https://github.com/gandarez/Hangfire/tree/manual-job

Changes are not tested by now.

### CODE REVIEW

**Comment by reaction1989** [comment]
@odinserj  What do you think about this?

**Comment by JesseKlaasse** [comment]
Any news on this? I would like this to be available in the main branch..

**Comment by BeeHiveJava** [comment]
Hey I'd love to see this merged into the main branch, this is a very useful feature @odinserj!

**Comment by BrutalSimplicity** [comment]
Is the remaining work, updating and adding tests to complete code coverage?

**Comment by BeeHiveJava** [comment]
Hey all, as @dcorbett-fivebridgesllc pointed out on #1036, there's an existing solution: https://github.com/tracstarr/Hangfire.Core.Dashboard.Management. This doesn't require breaking changes to Hangfire.

**Pull request closed without merging**
