### PR TITLE
[Dashboard] Adding DefaultRecordsPerPage on DashboardOptions

### PR DESCRIPTION
**Pull request by PaulARoy**
This derives from the awesome work of @JesseKlaass on this PR: #937

It focuses only on parametrized default number of records per page with a `DefaultRecordsPerPage` option on DashboardOptions.

Things to consider:
- DefaultRecordsPerPage is set to 10 by default, as existing

I am open to suggestions and improvements if you want!

### CODE REVIEW

**Comment by PaulARoy** [comment]
CI failed for a reason unrelated to the PR (fetch of .net framework timed out)

**Comment by odinserj** [comment]
Thank you again @PaulARoy, I've scheduled this PR also to Hangfire 1.7.12, since changes are small again. As a note for myself – we'll need to add @JesseKlaasse as co-author when merging this PR.

**Comment by PaulARoy** [comment]
Clearly!
This is mainly his work; I merely adapted.

**Comment by odinserj** [comment]
Great you decided to split the PR, it's much easier to accept the changes.

**Comment by PaulARoy** [comment]
Agreed, some minor improvements were really nice to add but some breaking changes blocked them. I plan to add very soon the arguments lists too (point 2 on #937) — probably this week-end if you want to wait.

By the way thanks for your awesome library. Really a must have on all my projects (including pro).

**Comment by odinserj** [comment]
Hi Paul, I've just implemented this feature with you as a co-author to avoid merging all the page changes. Thank you for the PR!

**Pull request closed without merging**
